### ISSUE TITLE
Failed to update github: 404-{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}

### ISSUE THREAD

**Issue by calaway** [ketiko/lois#19]
Lois stopped reporting the status check when running on one of our repos on CircleCI a few days ago. Upon further inspection it is throwing this error.
```
Failed to update github: 404-{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/statuses/#create-a-status"}
```

Example CircleCI build: https://circleci.com/gh/octanner/daito/935

Nothing had recently changed in terms of the CircleCI config in the repo or the env vars on Circle.

Any thoughts on how to address this?

**Comment by ketiko** [comment]
If you are using SSO with Github, have you enabled the `GITHUB_CREDENTIALS` token with your SSO provider?  It might be failing if you recently enabled SSO on your organization and the token isn't approved yet. @calaway

**Comment by ketiko** [comment]
You can check them here [https://github.com/settings/tokens](https://github.com/settings/tokens)

**Comment by ketiko** [comment]
I've seen github return 404 when it's because the authorization is denied and you'd typically expect a 403 forbidden instead.

**Comment by calaway** [comment]
Thank you. This helped me get to the bottom of it. 

The problem was that the GitHub bot whose token was being used by Lois to report back from CircleCI had somehow been removed as a collaborator on the repo. I added the bot back as a collaborator and it solved the problem.

**Comment by calaway** [comment]
Thank you. This helped me get to the bottom of it. 

The problem was that the GitHub bot whose token was being used by Lois to report back from CircleCI had somehow been removed as a collaborator on the repo. I added the bot back as a collaborator on GitHub and it solved the problem.

**Comment by calaway** [comment]
For posterity:

Error code 403: unauthorized (missing or invalid auth token on CircleCI)

Error code 404: not found (valid auth token on CircleCI, but either the repo you're reporting to does not exist or the owner of the token does not have access to that repo)
